language: java
jdk:
  - oraclejdk8
sudo: 
  - required
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install python-pip python-dev build-essential 
  - pip install pexpect
script:
  - mvn assembly:assembly
after_success:
  - python ./scripts/deploy.py